### PR TITLE
Omit metadata and fix column headers for large datasets

### LINKED ISSUE #2: Response header for large datasets might not include field names
## Issue
To get the dataset column headers (field names), currently we check for the response header **X-SODA2-Fields**. However for large datasets that header might be omitted as mentioned [here](https://dev.socrata.com/docs/response-codes.html]) which causes `_fetchResource` to throw a TypeError

## Expected Behavior
Should return the column headers for the dataset

## Actual Behavior
Throws error for large datasets

Screen Shot 2021-05-18 at 12 58 38 PM

## Specifications

  - Version: 1.1.1
  - Platform: macOS Big Sur

### PR DESCRIPTION
**Pull request by hawyar**
- The the first commit should have been with the previous PR but it was merged before I was able to do another commit. Cleaned up testing to be more consistent. 

- Second commit fixes #2, for large datasets that do not return`X-SODA2-Fields` we just peek at keys of the the first object. Assuming all objects have the same keys.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -130,6 +130,8 @@ class CMSClient {
 
       await this._fetchResourceMetadata();
 
+      if (!this.fetchOptions.includeMetadata) delete this.fetched.metadata;
```
Comment (ccali11) [inline index.js]: Great work per usual, @hawyar . A couple style / design questions for you / @shanejearley :

1. Do we use switch statements as a company? They have drawbacks and pushback from the broader JavaScript community, but this here is a simple use case and it appears to work just fine here. Not pushing one way or the other, just throwing this out there because it came to mind when I saw it.
2. What's the reason for using the delete operator instead of setting value to a falsy value in line 133 (and other places) `delete this.fetched.metadata`? To reduce space? Arbitrary design choice? Or perhaps another valid reason.

Again, code appears functional and well-written. Just bringing this up for discussion to learn and improve together. :)

File: index.js [hunk 2]
```diff
@@ -122,22 +122,26 @@ class CMSClient {
       const resourceData = await fetch(this.url);
       const headers = await resourceData.headers;
 
-      this.fetched.fields = JSON.parse(
-        headers.get('x-soda2-fields').split(','),
-      );
+      if (headers.get('x-soda2-fields')) {
```
Comment (ccali11) [inline index.js:125]: Confirming my understanding that this headers is available because CMS data is accessible through a Socrata-based API? Is that correct, @hawyar.

**Review by ccali11 — COMMENTED** [review]
@hawyar @shanejearley - Reviewed and looks great! Made a few comments with requiring responses, but very low urgency.

File: index.js (hunk 2 above)
Comment (hawyar) [reply index.js:125]: Yes, here is the list https://dev.socrata.com/docs/response-codes.html of available headers.

File: index.js [hunk 3]
```diff
@@ -122,20 +122,26 @@ class CMSClient {
...
+        );
+      }
+
       this.isOutdated = headers.get('x-soda2-data-out-of-date');
       this.lastModified = headers.get('Last-Modified');
 
       await this._fetchResourceMetadata();
 
-      switch (this.type) {
+      switch (this.fetchOptions.output) {
```
Comment (shanejearley) [inline index.js:136]: Since we are just checking a string here, how about using an object lookup that returns an arrow function based on the selected output option (and can default to json as you've done)?

Also, maybe the switch case works better here for now without needing to do any refactoring.

File: index.js (hunk 1 above)
Comment (shanejearley) [reply index.js]: Commented on the switch statement on line 136, Chris. This might just be one of those cases where the switch works well!

Comment (hawyar) [reply index.js]: @ccali11 most of these design decisions were based on my early assumptions with some arbitrary design choices, they are all subject to change.

1. We can remove the switch statement and have json as the default output and only change if client chooses csv. Something similar to what @shanejearley suggested below.

2. You are correct, using `delete` is less performant. I could have just set it to `undefined` however I did want to return undefined properties to the client that might cause trouble when they iterate over the returned object. What about creating a new object instead of mutating?

Comment (ccali11) [reply index.js]: Sounds good on all fronts!

File: index.js (hunk 3 above)
Comment (ccali11) [reply index.js:136]: Shane - for my learning purposes, can you explain what you mean by 
#returns an arrow function based on the selected output option
? 

Re: switch statements, I'm not opposed to using them here - I don't see any issues with the code - I just know they can cause issues in other situations so some org's decide against using them completely. Not a stickler, for better or for worse.

Comment (shanejearley) [reply index.js:136]: Something like
```
// fn to format output
async _formatResourceData(output) {
  const formats = {
    'csv': async () => {
      this.fetched.data = await resourceData.text();
    },
    'default': async () => {
      this.fetched.data = await resourceData.json();
      if (!this.fetched.fields.length) {
        this.fetched.fields = Object.keys(this.fetched.data[0]);
      }
    }
  }
  (formats[output] || formats['default'])()
};

// call it
this._formatResourceData[this.fetchOptions.output]
```
But it's not much more readable in this case and adds another fn with side effects. Agreeing that the switch or an if/else works best here!

Comment (hawyar) [reply index.js:136]: @shanejearley Is this similar to what you mentioned? This is a good refactor but since we want to perform some action based on the type don't we have to do another check after this lookup? 
```js
const resolveOutputType = (opt) => {
    let options = {
        json: 'json',
        csv: 'csv'
    }
    return options[opt]
}
```
@ccali11 I agree with you regarding the switch statement. For now we only have two options so I think an if/else or a switch statement as we have it would be enough.

Comment (shanejearley) [reply index.js:136]: Just submitted my comment above, not sure if you saw it before @hawyar

Comment (hawyar) [reply index.js:136]: @shanejearley I like this approach it looks great. Do you want to add that in a future PR? so I can merge this

Comment (shanejearley) [reply index.js:136]: Yes I'll copy it down!
